"""Create session_context, conversation_messages, and token_usage_stats tables

Revision ID: e02a290b0975
Revises: 001
Create Date: 2026-01-16 15:22:22.379572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e02a290b0975'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_message_id', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.Enum('aliyun', 'local', 'none', name='modelused'), nullable=True),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('query_id', sa.String(length=100), nullable=True),
    sa.Column('analysis_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_message_id'], ['conversation_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_parent', 'conversation_messages', ['parent_message_id'], unique=False)
    op.create_index('idx_session_turn', 'conversation_messages', ['session_id', 'turn'], unique=False)
    op.create_table('session_context',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('context_type', sa.Enum('local_model', 'aliyun_model', name='contexttype'), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('last_summary_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_usage_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('model_type', sa.Enum('local', 'aliyun', name='modeltype'), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('idx_dictionary_table_unique'), table_name='dictionary_table')
    op.drop_index(op.f('unique_entry'), table_name='dictionary_table')
    op.drop_table('dictionary_table')
    op.drop_table('data_sources')
    op.drop_index(op.f('idx_data_dictionary_source_id'), table_name='data_dictionary')
    op.drop_table('data_dictionary')
    op.drop_index(op.f('idx_query_history_created_at'), table_name='query_history')
    op.drop_index(op.f('idx_query_history_user_id'), table_name='query_history')
    op.drop_table('query_history')
    op.drop_index(op.f('idx_query_sessions_session_id'), table_name='query_sessions')
    op.drop_index(op.f('idx_query_sessions_user_id'), table_name='query_sessions')
    op.drop_table('query_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_sessions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('conversation', mysql.JSON(), nullable=True),
    sa.Column('last_active', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('query_sessions_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_query_sessions_user_id'), 'query_sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_query_sessions_session_id'), 'query_sessions', ['session_id'], unique=False)
    op.create_table('query_history',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('query_text', mysql.TEXT(), nullable=False),
    sa.Column('generated_sql', mysql.TEXT(), nullable=True),
    sa.Column('chart_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('result_data', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('query_history_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_query_history_user_id'), 'query_history', ['user_id'], unique=False)
    op.create_index(op.f('idx_query_history_created_at'), 'query_history', ['created_at'], unique=False)
    op.create_table('data_dictionary',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('column_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('alias_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('data_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('unit', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('data_dictionary_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_data_dictionary_source_id'), 'data_dictionary', ['source_id'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('type', mysql.ENUM('mysql', 'excel', 'api'), nullable=False),
    sa.Column('connection_string', mysql.TEXT(), nullable=True),
    sa.Column('file_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dictionary_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('field_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('value', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('label', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('sort_order', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('unique_entry'), 'dictionary_table', ['table_name', 'field_name', 'value'], unique=True)
    op.create_index(op.f('idx_dictionary_table_unique'), 'dictionary_table', ['table_name', 'field_name', 'value'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.drop_table('token_usage_stats')
    op.drop_table('session_context')
    op.drop_index('idx_session_turn', table_name='conversation_messages')
    op.drop_index('idx_parent', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    # ### end Alembic commands ###
